apiVersion: apps/v1             # API version
kind: Deployment                # Type of kubernetes resource
metadata:
  name: social-login-app-client      # Name of the kubernetes resource
spec:
  replicas: 1                   # No of replicas/pods to run
  selector:                     
    matchLabels:                # This deployment applies to Pods matching the specified labels
      app: social-login-app-client
  template:                     # Template for creating the Pods in this deployment
    metadata:
      labels:                   # Labels that will be applied to all the Pods in this deployment
        app: social-login-app-client
    spec:                       # Spec for the containers that will run inside the Pods
      containers:
      - name: social-login-app-client
        image: aymenmech96/frontend:0.0.10
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80   # Should match the Port that the container listens on
        resources:
          limits:
            cpu: 0.2
            memory: "10Mi"
---
apiVersion: v1                  # API version
kind: Service                   # Type of kubernetes resource
metadata:
  name: social-login-app-client      # Name of the kubernetes resource
  annotations:
    # Annotation pour utiliser l'adresse IP statique créée avec Terraform
    cloud.google.com/load-balancer-ip: "34.116.249.163"
spec:
  type: LoadBalancer            # Exposer le service via un équilibreur de charge externe
  # Spécifier l'adresse IP statique
  loadBalancerIP: "34.116.249.163"
  selector:
    app: social-login-app-client     # Any Pod matching the label `app=social-login-app-client` will be picked up by this service
  ports:                        # Forward incoming connections on port 80 to the target port 80 in the Pod
  - name: http
    port: 80
    targetPort: 80
